# ../tasks/main.yml
# Main ANSIBLE-GROUP-ROLE file that agregates all configuration tasks
# Contains only include statements for role
# -
# Prepare all ncessary dependancies for role
- name: Prepare dependancies 
  include: "{{ansible_os_family|lower}}_deps.yml"
  become: true
  tags: ['deps','full-role-run']

# Start group configuration part
- name: Configure Groups
  include: configure_groups.yml
  when: system_groups is defined
  become: true
  tags: ['groups','full-role-run']

# Start user configuration part
- name: Configure Users
  include: configure_users.yml
  when: system_users is defined
  become: true
  tags: ['users','full-role-run']

# Start group sudo configuration part
- name: Configure sudo status for groups
  include: configure_sudoers.yml
  become: true
  tags: ['sudo','full-role-run']
